# Generated by Django 5.0.6 on 2024-05-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, upload_to='thread_images'),
        ),
    ]
