# Generated by Django 5.0.3 on 2024-03-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articlecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'article categories'},
        ),
    ]
