# Generated by Django 5.0.4 on 2024-05-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_header_image_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
